kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: deployment
spec:
  replicas: 3
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80