kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
spec:
  replicas: $REPLICAS
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: nginx
      version: v01
  template:
    metadata:
      labels:
        app: ${APP}
        version: v01
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80